name = "worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[builder_config]
build_command = "npm run build"
upload_format = "service-worker"
src_dir = "src"
build_dir = "dist"
